#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         typesafety
version:      0.01
version_from: typesafety.pm
installdirs:  site
requires:
    B::Generate:                   1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
